/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Achievement: typeof import('./src/components/home/achievement.vue')['default']
    BulletinBoardRecommend: typeof import('./src/components/channel/bulletin-board-recommend.vue')['default']
    Cardio: typeof import('./src/components/cardio.vue')['default']
    Carousel: typeof import('./src/components/channel/carousel.vue')['default']
    ChatsList: typeof import('./src/components/chats-list/chats-list.vue')['default']
    ChatView: typeof import('./src/components/chat-view/chat-view.vue')['default']
    ChatViewHeader: typeof import('./src/components/chat-view/header/chat-view-header.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Empty: typeof import('./src/components/list/empty.vue')['default']
    FileBox: typeof import('./src/components/home/file-box.vue')['default']
    Knob: typeof import('primevue/knob')['default']
    LabeledToggle: typeof import('./src/components/minor-custom/labeled-toggle.vue')['default']
    Listbox: typeof import('primevue/listbox')['default']
    MessageBox: typeof import('./src/components/chat-view/message-box/message-box.vue')['default']
    MessageBubble: typeof import('./src/components/chat-view/message-box/components/message-bubble.vue')['default']
    Microprogram: typeof import('./src/components/home/microprogram.vue')['default']
    MuiEmpty: typeof import('./src/components/list/mui-empty.vue')['default']
    NewsPanel: typeof import('./src/components/channel/news-panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/sidebar.vue')['default']
    Status: typeof import('./src/components/home/status.vue')['default']
    StatusContainer: typeof import('./src/components/chat-view/message-box/components/status-container.vue')['default']
    StatusSending: typeof import('./src/components/chat-view/message-box/components/status-sending.vue')['default']
    StatusSent: typeof import('./src/components/chat-view/message-box/components/status-sent.vue')['default']
    StatusUnread: typeof import('./src/components/chat-view/message-box/components/status-unread.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TodoList: typeof import('./src/components/home/todo-list.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
